# Generated by Django 5.1.4 on 2025-05-12 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='category',
            field=models.CharField(choices=[('recording', 'Запись'), ('mixing', 'Сведение'), ('instrumental', 'Написание инструментала'), ('lyrics', 'Написание текста'), ('full_song', 'Песня под ключ')], default='recording', max_length=20),
        ),
        migrations.CreateModel(
            name='FullSongServiceParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('references', models.FileField(upload_to='full_song_refs/')),
                ('deadline', models.DateTimeField()),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='full_song_params', to='studio.service')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentalServiceParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('references', models.FileField(upload_to='instrumental_refs/')),
                ('remake_beat', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField()),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instrumental_params', to='studio.service')),
            ],
        ),
        migrations.CreateModel(
            name='LyricsServiceParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('references', models.FileField(upload_to='lyrics_refs/')),
                ('deadline', models.DateTimeField()),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics_params', to='studio.service')),
            ],
        ),
        migrations.CreateModel(
            name='MixingServiceParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(upload_to='mixing_zips/')),
                ('references', models.FileField(upload_to='mixing_refs/')),
                ('express', models.BooleanField(default=False)),
                ('mastering', models.BooleanField(default=True)),
                ('deadline', models.DateTimeField()),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mixing_params', to='studio.service')),
            ],
        ),
        migrations.CreateModel(
            name='RecordingServiceParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_type', models.CharField(choices=[('instrument', 'Инструмент'), ('vocal', 'Вокал')], max_length=20)),
                ('hours', models.IntegerField()),
                ('unknown_hours', models.BooleanField(default=False)),
                ('sound_engineer', models.BooleanField()),
                ('datetime', models.DateTimeField()),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording_params', to='studio.service')),
            ],
        ),
    ]
