# Generated by Django 5.1.4 on 2025-05-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_service_comment_servicetype_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='date_confirmed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтвержден'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='pending', max_length=20),
        ),
    ]
